# Generated by Django 4.1.3 on 2023-01-26 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=20, verbose_name='Apellido')),
            ],
        ),
        migrations.CreateModel(
            name='Instalacion',
            fields=[
                ('nro_contrato', models.IntegerField(primary_key=True, serialize=False, verbose_name='Número de Contrato')),
                ('nombre_cliente', models.CharField(blank=True, max_length=120, null=True, verbose_name='Nombre del Cliente')),
                ('direccion', models.TextField(blank=True, max_length=400, null=True, verbose_name='Dirección')),
                ('numero_telefono1', models.CharField(blank=True, max_length=13, null=True, verbose_name='Número de Teléfono 1')),
                ('numero_telefono2', models.CharField(blank=True, max_length=13, null=True, verbose_name='Número de Teléfono 2')),
                ('plan', models.CharField(choices=[['BP', 'BÁSICO PLUS'], ['BA', 'BÁSICO'], ['BR', 'BRONCE'], ['PL', 'PLATA'], ['OR', 'ORO']], default=0, max_length=12, verbose_name='Plan')),
                ('prioridad', models.IntegerField(choices=[[1, 'Baja'], [2, 'Media'], [3, 'Alta']], default=1, verbose_name='Prioridad')),
                ('tiempo_estimado', models.IntegerField(choices=[[1, '00:30'], [2, '01:00'], [3, '01:30'], [4, '02:00'], [5, '02:30'], [6, '03:00'], [7, '03:30'], [8, '04:00'], [9, '04:30'], [10, '05:00'], [11, '05:30'], [12, '06:00']], default=2, verbose_name='Tiempo estimado (en horas)')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('status', models.IntegerField(choices=[[0, 'Por Asignar'], [1, 'Asignada'], [2, 'Completada']], default=0, verbose_name='Status')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('hora', models.IntegerField(blank=True, choices=[[0, '08:00'], [1, '08:30'], [2, '09:00'], [3, '09:30'], [4, '10:00'], [5, '10:30'], [6, '11:00'], [7, '11:30'], [8, '12:00'], [9, '12:30'], [10, '13:00'], [11, '13:30'], [12, '14:00'], [13, '14:30'], [14, '15:00'], [15, '15:30'], [16, '16:00'], [17, '16:30'], [18, '17:00'], [19, '17:30']], null=True, verbose_name='Hora')),
                ('tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agenda.tecnico', verbose_name='Técnico')),
            ],
        ),
    ]
