# Generated by Django 4.1.3 on 2023-02-08 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_alter_instalacion_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instalacion',
            name='plan',
            field=models.CharField(choices=[['BP', 'BÁSICO PLUS'], ['BA', 'BÁSICO'], ['BR', 'BRONCE'], ['PL', 'PLATA'], ['OR', 'ORO'], ['EMP', 'EMPRESA']], default=0, max_length=12, verbose_name='Plan'),
        ),
    ]
