# Generated by Django 4.1.3 on 2023-02-15 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_alter_instalacion_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instalacion',
            name='plan',
            field=models.CharField(choices=[['BP', 'BÁSICO PLUS'], ['BA', 'BÁSICO'], ['BR', 'BRONCE'], ['PL', 'PLATA'], ['OR', 'ORO'], ['EMP', 'EMPRENDEDOR'], ['PRD', 'PRODUCTIVO'], ['PRDP', 'PRODUCTIVO PRO'], ['VISP', 'VISIONARIO PRO']], default=0, max_length=12, verbose_name='Plan'),
        ),
        migrations.AlterField(
            model_name='instalacion',
            name='tiempo_estimado',
            field=models.IntegerField(choices=[[1, '00:30'], [2, '01:00'], [3, '01:30'], [4, '02:00'], [5, '02:30'], [6, '03:00'], [7, '03:30'], [8, '04:00'], [9, '04:30'], [10, '05:00'], [11, '05:30'], [12, '06:00']], default=3, verbose_name='Tiempo estimado (en horas)'),
        ),
    ]
